In [1]:
#lets import pandas and load a new data set
import os
import pandas as pd

In [2]:
#load the dataset
mh = pd.read_csv("E:\CODE\Pandas\smmh.csv")
mh

,Timestamp,1. What is your age?,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,5/21/2022 23:38:28,24.0,Male,Single,Salaried Worker,"University, Private",Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,3,4,3,4,4,2,4,3,4,4
477,5/22/2022 0:01:05,26.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,...,2,3,4,4,4,2,4,4,4,1
478,5/22/2022 10:29:21,29.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,...,4,3,2,3,3,3,4,2,2,2
479,7/14/2022 19:33:47,21.0,Male,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,...,2,3,3,2,2,3,4,4,5,4
480,11/12/2022 13:16:50,53.0,Male,Married,Salaried Worker,Private,Yes,"Facebook, YouTube",Less than an Hour,2,...,1,3,1,1,3,3,2,2,2,3

# Renaming
- `rename()` allows you to change index names and/or column names.

In [7]:
#lets rename the columns in our dataset
renamed = mh.rename(columns={"1. What is your age?":"age"})
renamed

,Timestamp,age,2. Gender,3. Relationship Status,4. Occupation Status,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,5/21/2022 23:38:28,24.0,Male,Single,Salaried Worker,"University, Private",Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,3,4,3,4,4,2,4,3,4,4
477,5/22/2022 0:01:05,26.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,...,2,3,4,4,4,2,4,4,4,1
478,5/22/2022 10:29:21,29.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,...,4,3,2,3,3,3,4,2,2,2
479,7/14/2022 19:33:47,21.0,Male,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,...,2,3,3,2,2,3,4,4,5,4
480,11/12/2022 13:16:50,53.0,Male,Married,Salaried Worker,Private,Yes,"Facebook, YouTube",Less than an Hour,2,...,1,3,1,1,3,3,2,2,2,3

In [9]:
#lets rename a few more columns
renamed = mh.rename(columns={"1. What is your age?":"age",
                            "2. Gender":"gender", 
                            "3. Relationship Status":"rel_status",
                            "4. Occupation Status":"occupation"})
renamed

,Timestamp,age,gender,rel_status,occupation,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
0,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
1,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,5/21/2022 23:38:28,24.0,Male,Single,Salaried Worker,"University, Private",Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,3,4,3,4,4,2,4,3,4,4
477,5/22/2022 0:01:05,26.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,...,2,3,4,4,4,2,4,4,4,1
478,5/22/2022 10:29:21,29.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,...,4,3,2,3,3,3,4,2,2,2
479,7/14/2022 19:33:47,21.0,Male,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,...,2,3,3,2,2,3,4,4,5,4
480,11/12/2022 13:16:50,53.0,Male,Married,Salaried Worker,Private,Yes,"Facebook, YouTube",Less than an Hour,2,...,1,3,1,1,3,3,2,2,2,3

In [10]:
# lets rename the index
renamed_index = renamed.rename(index={0: "first_entry", 1: "second_entry"})
renamed_index

,Timestamp,age,gender,rel_status,occupation,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
first_entry,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
second_entry,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,5/21/2022 23:38:28,24.0,Male,Single,Salaried Worker,"University, Private",Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,3,4,3,4,4,2,4,3,4,4
477,5/22/2022 0:01:05,26.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,...,2,3,4,4,4,2,4,4,4,1
478,5/22/2022 10:29:21,29.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,...,4,3,2,3,3,3,4,2,2,2
479,7/14/2022 19:33:47,21.0,Male,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,...,2,3,3,2,2,3,4,4,5,4
480,11/12/2022 13:16:50,53.0,Male,Married,Salaried Worker,Private,Yes,"Facebook, YouTube",Less than an Hour,2,...,1,3,1,1,3,3,2,2,2,3

You'll probably rename columns very often, but rename index values very rarely. For that, `set_index()` is usually more convenient.

Both the row index and the column index can have their own `name` attribute. The complimentary `rename_axis()` method may be used to change these names.

In [13]:
# lets rename the index name of rows to "entries" and the columns to "fields"
renamed_idx2 = renamed_index.rename_axis("entries", axis = "rows").rename_axis("fields", axis ="columns")
renamed_idx2

fields,Timestamp,age,gender,rel_status,occupation,5. What type of organizations are you affiliated with?,6. Do you use social media?,7. What social media platforms do you commonly use?,8. What is the average time you spend on social media every day?,9. How often do you find yourself using Social media without a specific purpose?,...,11. Do you feel restless if you haven't used Social media in a while?,"12. On a scale of 1 to 5, how easily distracted are you?","13. On a scale of 1 to 5, how much are you bothered by worries?",14. Do you find it difficult to concentrate on things?,"15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?","16. Following the previous question, how do you feel about these comparisons, generally speaking?",17. How often do you look to seek validation from features of social media?,18. How often do you feel depressed or down?,"19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?","20. On a scale of 1 to 5, how often do you face issues regarding sleep?"
entries,,,,,,,,,,,,,,,,,,,,,
first_entry,4/18/2022 19:18:47,21.0,Male,In a relationship,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,...,2,5,2,5,2,3,2,5,4,5
second_entry,4/18/2022 19:19:28,21.0,Female,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,...,2,4,5,4,5,1,1,5,4,5
2,4/18/2022 19:25:59,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,...,1,2,5,4,3,3,1,4,2,5
3,4/18/2022 19:29:43,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram",More than 5 hours,4,...,1,3,5,3,5,1,2,4,3,2
4,4/18/2022 19:33:31,21.0,Female,Single,University Student,University,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,5/21/2022 23:38:28,24.0,Male,Single,Salaried Worker,"University, Private",Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,...,3,4,3,4,4,2,4,3,4,4
477,5/22/2022 0:01:05,26.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,...,2,3,4,4,4,2,4,4,4,1
478,5/22/2022 10:29:21,29.0,Female,Married,Salaried Worker,University,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,...,4,3,2,3,3,3,4,2,2,2
479,7/14/2022 19:33:47,21.0,Male,Single,University Student,University,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,...,2,3,3,2,2,3,4,4,5,4
480,11/12/2022 13:16:50,53.0,Male,Married,Salaried Worker,Private,Yes,"Facebook, YouTube",Less than an Hour,2,...,1,3,1,1,3,3,2,2,2,3

# Combining
Three methods:
- `concat()`- given a list of elements, this function will smush those elements together along an axis
- `join()`
- `merge()`

In [14]:
#load new datasets
brands = pd.read_csv("brands.csv")
similar = pd.read_csv("similarweb.csv")

#concatenate both dataframes
concat_brands = pd.concat([brands, similar])

concat_brands

,name,site,wikipedia,wikipedia_languages_num,twitter,twitter_following,twitter_followers,twitter_tweets,twitter_verified,facebook,...,social2_name,social2_percent,social3_name,social3_percent,social4_name,social4_percent,social5_name,social5_percent,total_outgoing_links,total_technologies
0,Nike,https://www.nike.com,https://en.wikipedia.org/wiki/Nike%2C_Inc.,75.0,/Nike,120.0,9863642.0,38544.0,v,/nike,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Adidas,https://www.adidas.com,https://en.wikipedia.org/wiki/Adidas,91.0,/adidas,200.0,4377037.0,15950.0,v,/adidas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Skechers,https://www.skechers.com,https://en.wikipedia.org/wiki/Skechers,17.0,/SKECHERSUSAx,238.0,48697.0,10615.0,NaN,/SKECHERS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,New Balance,https://www.newbalance.com,https://en.wikipedia.org/wiki/New_Balance,32.0,/NewBalance,728.0,294664.0,19446.0,v,/Newbalance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ASICS,https://www.asics.com/us/en-us,https://en.wikipedia.org/wiki/Asics,35.0,/ASICSamerica,1492.0,97233.0,15699.0,x,/ASICS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Puma,https://us.puma.com/us/en,https://en.wikipedia.org/wiki/Puma_(brand),60.0,/puma,63.0,1998499.0,73747.0,v,/puma,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Under Armour,https://www.underarmour.com/en-us,https://en.wikipedia.org/wiki/Under_Armour,32.0,/UnderArmour,925.0,963820.0,26950.0,v,/UnderArmour,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Fila,https://www.fila.com,https://en.wikipedia.org/wiki/Fila,35.0,/filausa,185.0,69851.0,8944.0,x,/FILAusa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Columbia,https://www.columbia.com/footwear,https://en.wikipedia.org/wiki/Columbia_Sportswear,14.0,/Columbia1938,3553.0,127710.0,23122.0,x,/ColumbiaSportswear,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,K-Swiss,https://kswiss.com,https://en.wikipedia.org/wiki/K-Swiss,12.0,/KSWISS,229.0,25028.0,15658.0,x,/kswiss,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Adidas,adidas.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Facebook,22.75,Youtube,20.57,Twitter,15.35,Pinterest,4.28,73.0,98.0
1,ASICS,asics.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Youtube,27.98,Facebook,20.27,Pinterest,7.97,Twitter,5.29,67.0,106.0
2,Columbia,columbia.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Reddit,33.38,Youtube,10.44,Twitter,1.61,Instagram,1.06,35.0,131.0
3,Fila,fila.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Youtube,30.29,Pinterest,5.78,Instagram,5.32,Reddit,0.28,3.0,70.0
4,K-Swiss,kswiss.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Facebook,22.31,Youtube,14.12,Discord,8.96,Instagram,7.95,6.0,84.0
5,New Balance,newbalance.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Linkedin,22.85,Reddit,13.86,Facebook,13.12,Pinterest,8.83,65.0,105.0
6,Nike,nike.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Facebook,29.09,Reddit,7.44,Twitter,6.37,Instagram,4.16,203.0,92.0
7,Puma,puma.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Youtube,22.89,Instagram,7.60,Pinterest,3.18,Twitter,2.93,67.0,109.0
8,Skechers,skechers.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Youtube,12.16,Pinterest,4.25,Reddit,3.95,Linkedin,2.47,28.0,89.0
9,Under Armour,underarmour.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Linkedin,21.87,Reddit,8.71,Youtube,7.86,Pinterest,2.00,33.0,103.0

In [15]:
#using join()

a = brands.set_index(["name", "site"])
b = similar.set_index(["name", "site"])

a.join(b, lsuffix = "aaa", rsuffix = "bbb")

a

,,wikipedia,wikipedia_languages_num,twitter,twitter_following,twitter_followers,twitter_tweets,twitter_verified,facebook,facebook_likes,facebook_followers,...,zippia_local,indeed,indeed_wellbeing,indeed_stars,indeed_reviews,indeed_revenue,mozcom_domain_authority,mozcom_linking_root_domains,mozcom_ranking_keywords,mozcom_spam_score
name,site,,,,,,,,,,,,,,,,,,,,,
Nike,https://www.nike.com,https://en.wikipedia.org/wiki/Nike%2C_Inc.,75,/Nike,120,9863642,38544,v,/nike,36842713,38667225,...,NaN,https://www.indeed.com/cmp/Nike,76,4.1,11.7K,more than $10B (USD),91,253.6k,241.3k,9
Adidas,https://www.adidas.com,https://en.wikipedia.org/wiki/Adidas,91,/adidas,200,4377037,15950,v,/adidas,41046633,41755214,...,Adidas America revenue: $ 510.0 million,https://www.indeed.com/cmp/Adidas,71,3.9,4.9K,more than $10B (USD),89,135.3k,106.6k,14
Skechers,https://www.skechers.com,https://en.wikipedia.org/wiki/Skechers,17,/SKECHERSUSAx,238,48697,10615,NaN,/SKECHERS,7634258,7664864,...,NaN,https://www.indeed.com/cmp/Skechers,69,3.5,2.8K,$5B to $10B (USD),80,32.3k,19k,7
New Balance,https://www.newbalance.com,https://en.wikipedia.org/wiki/New_Balance,32,/NewBalance,728,294664,19446,v,/Newbalance,9035045,9127640,...,NaN,https://www.indeed.com/cmp/New-Balance,72,3.9,806,$1B to $5B (USD),82,36.1k,37.6k,2
ASICS,https://www.asics.com/us/en-us,https://en.wikipedia.org/wiki/Asics,35,/ASICSamerica,1492,97233,15699,x,/ASICS,4.5M,x,...,ASICS America revenue: $ 110.5 billion,https://www.indeed.com/cmp/Asics,74,3.9,470,more than $10B (USD),75,46.2k,25.5k,3
Puma,https://us.puma.com/us/en,https://en.wikipedia.org/wiki/Puma_(brand),60,/puma,63,1998499,73747,v,/puma,21M,x,...,NaN,https://www.indeed.com/cmp/Puma,72,4.0,1K,$5B to $10B (USD),88,72k,21.5k,1
Under Armour,https://www.underarmour.com/en-us,https://en.wikipedia.org/wiki/Under_Armour,32,/UnderArmour,925,963820,26950,v,/UnderArmour,11639540,11651501,...,NaN,"https://www.indeed.com/cmp/Under-Armour,-Inc",74,3.8,1.5K,$5B to $10B (USD),73,41.4k,59.5k,1
Fila,https://www.fila.com,https://en.wikipedia.org/wiki/Fila,35,/filausa,185,69851,8944,x,/FILAusa,264K,303K,...,NaN,https://www.indeed.com/cmp/Fila,x,4.0,52,x,60,12.2k,5.4k,1
Columbia,https://www.columbia.com/footwear,https://en.wikipedia.org/wiki/Columbia_Sportswear,14,/Columbia1938,3553,127710,23122,x,/ColumbiaSportswear,2432333,2453789,...,NaN,https://www.indeed.com/cmp/Columbia-Sportswear...,74,3.7,926,$1B to $5B (USD),66,22.2k,46.9k,4
K-Swiss,https://kswiss.com,https://en.wikipedia.org/wiki/K-Swiss,12,/KSWISS,229,25028,15658,x,/kswiss,916K,x,...,NaN,https://www.indeed.com/cmp/K--swiss,x,3.8,4,$100M to $500M (USD),58,5.9k,2k,3